BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE WORD_WORDBANK_RELATION';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MEMBER_WORD_RELATION';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE WORDBANK';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AUTHORITIES';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MEMBER';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AUTH_INFO';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE WORD';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE MEMBER_NO_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE WORD_NO_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE WORDBANK_NO_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE WORD_WORDBANK_RELATION_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE MEMBER_WORD_RELATION_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;

CREATE TABLE MEMBER
(
    NO            NUMBER(10)                NOT NULL,
    EMAIL         VARCHAR2(50) UNIQUE       NOT NULL,
    PASSWORD      VARCHAR2(60)              NOT NULL,
    CREATE_DATE   DATE      DEFAULT SYSDATE NOT NULL,
    MODIFIED_DATE DATE      DEFAULT SYSDATE NOT NULL,
    DEL_FLAG      CHAR(1)   DEFAULT 0       NOT NULL,
    CERTIFY_FLAG  CHAR(1)   DEFAULT 0       NOT NULL,
    GRADE         NUMBER(2) DEFAULT 0       NOT NULL
);

CREATE TABLE AUTH_INFO
(
    MEMBER_NO   NUMBER(10)           NOT NULL,
    NO          VARCHAR2(200)        NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE AUTHORITIES
(
    MEMBER_NO NUMBER(10)                       NOT NULL,
    AUTHORITY VARCHAR2(50) DEFAULT 'ROLE_USER' NOT NULL
);

CREATE TABLE WORD
(
    NO        NUMBER(6)           NOT NULL,
    WORD      VARCHAR2(50)        NOT NULL,
    HURIGANA  VARCHAR2(50)        NULL,
    OKURIGANA VARCHAR2(50)        NULL,
    YOMIGANA  VARCHAR2(50)        NOT NULL,
    MEAN      VARCHAR2(50)        NOT NULL,
    GRADE     NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE WORDBANK
(
    NO            NUMBER(14)              NOT NULL,
    OWNER_NO      NUMBER(10)              NOT NULL,
    NAME          VARCHAR2(50)            NOT NULL,
    CREATE_DATE   DATE    DEFAULT SYSDATE NOT NULL,
    MODIFIED_DATE DATE    DEFAULT SYSDATE NOT NULL,
    DEL_FLAG      CHAR(2) DEFAULT 0       NOT NULL
);

CREATE TABLE WORD_WORDBANK_RELATION
(
    NO            NUMBER(20)           NOT NULL,
    WORD_NO       NUMBER(6)            NOT NULL,
    WORDBANK_NO   NUMBER(14)           NOT NULL,
    CREATE_DATE   DATE DEFAULT SYSDATE NOT NULL,
    MODIFIED_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE MEMBER_WORD_RELATION
(
    NO        NUMBER(16) NOT NULL,
    MEMBER_NO NUMBER(10) NOT NULL,
    WORD_NO   NUMBER(6)  NOT NULL
);

ALTER TABLE MEMBER
    ADD CONSTRAINT PK_MEMBER PRIMARY KEY (NO);

ALTER TABLE WORD
    ADD CONSTRAINT PK_WORD PRIMARY KEY (NO);

ALTER TABLE WORDBANK
    ADD CONSTRAINT PK_WORDBANK PRIMARY KEY (NO);

ALTER TABLE WORD_WORDBANK_RELATION
    ADD CONSTRAINT PK_WORD_WORDBANK_RELATION PRIMARY KEY (NO);

ALTER TABLE MEMBER_WORD_RELATION
    ADD CONSTRAINT PK_MEMBER_WORD_RELATION PRIMARY KEY (NO);

ALTER TABLE WORDBANK
    ADD CONSTRAINT FK_MEMBER_NO FOREIGN KEY (OWNER_NO)
        REFERENCES MEMBER (NO);

ALTER TABLE WORD_WORDBANK_RELATION
    ADD CONSTRAINT FK_WORD_NO FOREIGN KEY (WORD_NO)
        REFERENCES WORD (NO);

ALTER TABLE WORD_WORDBANK_RELATION
    ADD CONSTRAINT FK_WORDBANK_NO FOREIGN KEY (WORDBANK_NO)
        REFERENCES WORDBANK (NO);

ALTER TABLE MEMBER_WORD_RELATION
    ADD CONSTRAINT FK_MEMBER_NO_2 FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER (NO);

ALTER TABLE MEMBER_WORD_RELATION
    ADD CONSTRAINT FK_WORD_NO_2 FOREIGN KEY (WORD_NO)
        REFERENCES WORD (NO);

ALTER TABLE AUTHORITIES
    ADD CONSTRAINT FK_MEMBER_NO_3 FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER (NO);

ALTER TABLE AUTH_INFO
    ADD CONSTRAINT FK_MEMBER_NO_4 FOREIGN KEY (MEMBER_NO)
        REFERENCES MEMBER (NO);

CREATE SEQUENCE MEMBER_NO_SEQ START WITH 1;
CREATE SEQUENCE WORD_NO_SEQ START WITH 1;
CREATE SEQUENCE WORDBANK_NO_SEQ START WITH 1;
CREATE SEQUENCE WORD_WORDBANK_RELATION_SEQ START WITH 1;
CREATE SEQUENCE MEMBER_WORD_RELATION_SEQ START WITH 1;

COMMENT ON COLUMN WORD.HURIGANA IS '한자읽는법';
COMMENT ON COLUMN WORD.OKURIGANA IS '히라가나부분 읽는법';
COMMENT ON COLUMN WORD.YOMIGANA IS '전체 읽는법';