INSERT INTO MEMBER(NO, EMAIL, PASSWORD) VALUES (MEMBER_NO_SEQ.nextval, 'puhahaha3000@naver.com', '$2a$10$Whnrir5hcDSTJXeopEj58Oc4lK2uaMH2yivfaZrXxu4/e.tWSwdzi');
INSERT INTO AUTHORITIES(MEMBER_NO) VALUES (MEMBER_NO_SEQ.currval);
COMMIT;